### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by cwa-cc** [odiseoteam/SyliusBannerPlugin#17]
In order to implement the plugin with :
- Sylius 1.12.0
- Symfony 6.2.1

Please update the part (4. Add the shop and admin routes) like that :
odiseo_sylius_banner_plugin_shop:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}/banners
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    defaults:
        _controller: odiseo_sylius_banner_plugin.controller.banner::indexAction

For me, this update work fine.

Thanks in advance.

**Comment by bigboss86** [comment]
Hello,
Feel free to contribute if you have time. This plugin will be free forever.
Thanks!

**Comment by bigboss86** [comment]
Fixed!
