### ISSUE TITLE
Small bug in routing

### ISSUE THREAD

**Issue by fanti001** [odiseoteam/SyliusBannerPlugin#18]
src/Resources/config/routing/shop/banner.yaml
now is
`  _controller: odiseo_sylius_banner_plugin.controller.banner:indexAction`
`...banner:indexAction`
is to be:
`_controller: odiseo_sylius_banner_plugin.controller.banner::indexAction`

`...banner::indexAction`

**Comment by bigboss86** [comment]
Hello,
Feel free to contribute if you have time. This plugin will be free forever.
Thanks!

**Comment by bigboss86** [comment]
Fixed!
