### ISSUE TITLE
Controller "odiseo_sylius_banner_plugin.controller.banner:indexAction" does neither exist as service nor as class

### ISSUE THREAD

**Issue by hous04** [odiseoteam/SyliusBannerPlugin#19]
Hi
I have followed the installation, th admin works and I can add banners but I get this error in the front:
`{{ render(url('odiseo_sylius_banner_plugin_shop_partial_banner', {'template': '@OdiseoSyliusBannerPlugin/Shop/Banner/_banner.html.twig'})) }}`

> An exception has been thrown during the rendering of a template ("The controller for URI "/fr_FR/banners/partial" is not callable: Controller "odiseo_sylius_banner_plugin.controller.banner:indexAction" does neither exist as service nor as class.").

**Comment by IHunte** [comment]
Did you find any solution ?, I'm running on the same issue.

**Comment by bigboss86** [comment]
Hi folks,
Duplicated issue: https://github.com/odiseoteam/SyliusBannerPlugin/issues/18
Feel free to contribute if you have time. This plugin will be free forever.
Thanks!

**Comment by bigboss86** [comment]
Fixed!
