### ISSUE TITLE
  You have requested a non-existent parameter "odiseo_sylius_banner.model.banner.class".

### ISSUE THREAD

**Issue by xDesignX** [odiseoteam/SyliusBannerPlugin#2]
Hi,

I just to add your bundle to sylius but I'm getting this error after command:

php bin/console doctrine:schema:update --force
  
You have requested a non-existent parameter "odiseo_sylius_banner.model.banner.class".

**Comment by songecko** [comment]
Hi @xDesignX  , you need to add the plugin in AppKernel (bundles.php) before the SyliusResource one. Did you do that?
Let me know if that solve the issue. Also feel free to contact me at Sylius Slack: http://sylius-devs.slack.com/team/U3FR368UC.

**Comment by xDesignX** [comment]
it works thank you very much !

**Comment by songecko** [comment]
You're welcome
