### ISSUE TITLE
Invalid form error on edit without image

### ISSUE THREAD

**Issue by GCalmels** [odiseoteam/SyliusBannerPlugin#3]
When I edit a banner, I have an error : `Image cannot be blank` because I do not post a new image... Is it possible to keep the previous posted image ?

**Comment by bigboss86** [comment]
Hi @GCalmels. We released a new version. This error should be fixed. Try it and tell me.
Thanks!

**Comment by GCalmels** [comment]
Hi, thanks for the new release and the fast reply !
