### ISSUE TITLE
Root folder issue

### ISSUE THREAD

**Issue by AnnevanVelden** [odiseoteam/SyliusBannerPlugin#4]
On our webserver we use the public_html as the root folder but the bundle still requires me to have a `public/media/banner-img` folder, it will refuse to upload any images if it doesn't have this folder. 
The main image does upload to the `public_html/media/banner-img` route when i added the public folder but the cache images don't upload at all. I've edited it so that the banner image is the original image due to this, is there any way to change the upload root of the bundle to use it to it's full potential?

**Comment by bigboss86** [comment]
Hi @AnnevanVelden. We release a new version changing the upload root folder to public directory.

**Comment by AnnevanVelden** [comment]
Thanks @bigboss86 it works perfectly now
