### ISSUE TITLE
Image size got much heavier after uploaded

### ISSUE THREAD

**Issue by charlesc-ai** [odiseoteam/SyliusBannerPlugin#7]
Hi
I have noticed that after uploaded images, the size became large than the original. For example, an image of 70kb, I got the uploaded image size 259kb, it's bad for SEO performance, do you have any idea?

Thanks

**Comment by odiseoteam** [comment]
Hi @charlesc-ai. I think this can be a problem of liip_imagine library when it generates the images, see this configuration: https://github.com/odiseoteam/SyliusBannerPlugin/blob/master/src/Resources/config/config.yaml.

Try to override the liip_imagine image definition and set the quality parameter: https://symfony.com/doc/current/bundles/LiipImagineBundle/configuration.html.

Also if you have the Liip Imagine Bundle version 2.4.0 it comes with webp support.

**Comment by charlesc-ai** [comment]
Thank you! It's very helpful, need to add liip_imagine setting, it works after adding parameters "quality", and "jpeg_quality", here is mine for reference:

liip_imagine:
    loaders:
        banner_image:
            filesystem:
                data_root: "%sylius_core.public_dir%/media/banner"
    filter_sets:
        odiseo_sylius_banner_plugin_image:
            quality: 60
            jpeg_quality: 60
            png_compression_level: ~
            png_compression_filter: ~
            animated: false
            format: ~
            data_loader: banner_image
            filters:
                thumbnail: { size: [2280, 1072], mode: outbound }

**Comment by xchopin** [comment]
How did you override the config.yaml file please? :)

**Comment by bigboss86** [comment]
Hi @xchopin. You can follow the Symfony standard:

https://symfony.com/doc/current/bundles/override.html#services-configuration

Regards.
